name: build and run tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        # install dependencies
        - name: Clang 12
          run: |
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 12
        - name: boost
          run: sudo apt-get update && sudo apt-get install -yq libboost1.71-dev
        - name: gtest
          run: |
            sudo apt-get install -yq libgtest-dev
            cd /usr/src/googletest/googletest
            sudo mkdir build
            cd build
            sudo cmake ..
            sudo make -j $(nproc)
        # build project
        - name: create build folder
          run: mkdir build
        - name: configure project
          run: |
            cd build
            cmake ..
            make -j $(nproc)
        - name: run tests
          run: ./FDCore_test
